CommunityApp/urls.py
from django.conf.urls import url
from django.urls import re_path

from CommunityApp import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^questions/$', views.questions_list, name='list'),
    re_path(r'^questions/(?P<qID>[0-9]+)/$', views.question_details, name='details'),
    re_path(r'^questions/add/$', views.add_question, name='addQuestion'),

]

CommunityPlateform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('CommunityApp.urls')),

]

CommunityApp/models.py
# A ajouter la fonctinnalité de marquer une publication comme inappropriée
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models


def isValidEmail(email):
    if str(email).endswith("tek-up.tn") == False:
        raise ValidationError(
            ('%(email) is not a TEK-UP Email'),
            params={'email': email},
        )

class User(models.Model):
    userName = models.CharField(default="username", max_length=30)
    name = models.CharField(default="name", max_length=30)
    email = models.EmailField(default="user@tek-up.tn", validators=[isValidEmail])

    def __str__(self):
        return self.userName


class Member(User):
    def get_num_publications(self):
        return Question.objects.filter(publisher=self).count() or 0


class Tag(models.Model):
    tagText = models.CharField(max_length=20)

    def __str__(self):
        return self.tagText


class Question(models.Model):
    questionTitle = models.CharField(max_length=30, default="Publication")
    questionText = models.TextField(validators=[MinLengthValidator(30)])
    isClosed = models.BooleanField(default=False)
    isValid = models.BooleanField(default=False)

    reports = models.ManyToManyField(
        'Member',
        through='QuestionReportsByUsers',
        # added to differ with the lead relation
        related_name='user_reports',
        blank=True,
    )

    publisher = models.ForeignKey(Member, default=None, on_delete=models.DO_NOTHING)
    solution = models.OneToOneField('Answer', blank=True, null=True, on_delete=models.CASCADE)
    tags = models.ManyToManyField(
        Tag,
        through='TagsInPublication',
        # added to differ with the lead relation
        related_name='publication_tags',
        blank=False,
    )

    def __str__(self):
        return self.questionTitle + " Text: " + self.questionText


class Answer(models.Model):
    answerText = models.TextField(default=None)

    publication = models.ForeignKey(Question, default=None, on_delete=None, blank=True)
    commenter = models.ForeignKey(Member, default=None, on_delete=models.DO_NOTHING)
    likers = models.ManyToManyField(
        Member,
        through='LikesByUsers',
        # added to differ with the lead relation
        related_name='comment_likers',
        blank=True,
    )

    reports = models.ManyToManyField(
        'Member',
        through='AnswerReportsByUsers',
        # added to differ with the lead relation
        related_name='answer_user_reports',
        blank=True,
    )

    def __str__(self):
        return self.answerText



class LikesByUsers(models.Model):
    comment = models.ForeignKey(Answer, default=None,on_delete=models.DO_NOTHING)
    member = models.ForeignKey(Member, default=None, on_delete= models.DO_NOTHING)


class QuestionReportsByUsers(models.Model):
    user = models.ForeignKey(Member, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    motif = models.TextField('motif', max_length=100)

class AnswerReportsByUsers(models.Model):
    user = models.ForeignKey(Member, on_delete=models.CASCADE)
    question = models.ForeignKey(Answer, on_delete=models.CASCADE)
    motif = models.TextField('motif', max_length=100)


class TagsInPublication(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    publication = models.ForeignKey(Question, on_delete=models.CASCADE)

CommunityApp/forms.py
from django import forms

from CommunityApp.models import Question


class AddQuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('questionTitle','questionText','publisher','tags')

CommunityApp/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth import logout, authenticate, login
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse
from django.views import generic
from django.views.generic import DetailView

from CommunityApp.forms import AddQuestionForm
from .models import *


def index(request):
    return render(request, 'index.html')

def questions_list(request):
    all_questions_list = Question.objects.all()
    return render(request, 'questions.html', {'questions_list': all_questions_list})

def question_details(request, qID):
    question = get_object_or_404(Question, pk=qID)
    tags = question.tags.all()
    return render(request,
                  'question_details.html',
                  {
                      'question': question,
                      'tags':tags
                   }
                  )


def add_question(request):
    if request.method == "GET":
        form = AddQuestionForm()
        return render(request, 'add_question.html', {'form': form})
    if request.method == "POST":
        form = AddQuestionForm(request.POST)
        if form.is_valid():
            postQuestion = form.save(commit=False)
            postQuestion.save()
            return HttpResponseRedirect(reverse('list'))
        else:
            return render(request, 'add_question.html',
                          {'msg_erreur': 'Erreur lors de la création du projet',
                           'form': form})

CommunityApp/templates/add_question.html
{% extends "base.html" %}
{% block header %}
         {% include "header.html" %}
{% endblock header %}

{% block content %}

{% if msg_erreur %}<p><strong>{{ msg_erreur }}:
 {% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
    </div>
{% endfor %}

</strong></p>{% endif %}
<form action="{% url 'addQuestion' %}" method="POST">
{% csrf_token %}
    <div class="container">
         <div class="form-group" >
              <div class="row">
                  <div class="col-2">
                    {{ form.as_p }}
                  </div>

                </div>
         </div>
        <input class="btn btn-primary" type="submit" value="Add Offer" />
    </div>
</form>
{% endblock %}
{% block footer %}
{% endblock %}

CommunityApp/templates/base.html
{% load static %}

<head>
    <meta charset="utf-8">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" media="screen">
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

</head>
<body>
    {% block header %}{% endblock %}
    {% block content %}{% endblock %}
    {% block footer %}{% endblock %}
</body>

CommunityApp/templates/footer.html
<div class="fixed-bottom">
<footer id="footer" class="footer row-fluid">
    <div class="span8 offset2">
        {% block footer_content %}
            <div>© 2018 - TEKUP - {% block footer_app_title %}Community App{% endblock footer_app_title %}
            </div>
        <div>by GLSI-TEKUP</div>
        {% endblock footer_content%}
    </div>
</footer>
</div>

CommunityApp/templates/header.html
{% block content %}
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{% url 'index' %}">HelpDesk App</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
                 <li class="nav-item active">
                <a class="nav-link" href="{% url 'list' %}">Questions <span class="sr-only">(current)</span></a>
              </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'addQuestion' %}">New Question <span class="sr-only">(current)</span></a>
              </li>



            </ul>
          </div>
        </nav>
    </div>
{% endblock %}

CommunityApp/templates/index.html
{% extends "base.html" %}
{% block header %}
         {% include "header.html" %}
{% endblock header %}

{% block content %}
<h1>Hello to Tekup Community App</h1>
{% endblock %}
{% block footer %}
    {% include "footer.html" %}
{% endblock %}

CommunityApp/templates/question_details.html
{% extends "base.html" %}
{% block header %}
         {% include "header.html" %}
{% endblock header %}

{% block content %}
<h3>{{ question.questionTitle }}</h3>
<p>{{ question.questionText }}</p>
<p>Publié par:{{ question.publisher.userName }}</p>
    {% if question.tagsinpublication_set.count > 0  %}
        <p>Tags</p>
        {% for tag in tags %}
            <p>{{ tag.tagText}}</p>
        {% endfor %}
    {% endif %}

{% endblock %}
{% block footer %}
    {% include "footer.html" %}
{% endblock %}

CommunityApp/templates/questions.html
{% extends "base.html" %}
{% load static %}
{% block header %}
         {% include "header.html" %}
{% endblock header %}

{% block content %}
<ul>
    {% for question in questions_list %}
            <div class="table-container">
							<table class="table table-filter">
								<tbody>
									<tr data-status="pagado">
										<td></td>
										<td></td>
										<td>
											<div class="media">
												<a href="#" class="pull-left">
													<img src="{% static 'images/icon_person.png'%}" class="media-photo" width="50%">
												</a>
												<div class="media-body">
													<h4 class="title">
														<li><a href="{% url 'details' question.id %}"> {{ question.questionTitle }}</a></li>
														<span class="pull-right pagado">{{ question.publisher }}</span>
													</h4>
													<p class="summary">{{ question.questionText }}</p>
												</div>
											</div>
										</td>
									</tr>
                                </tbody>
                            </table>
    </div>
    {% endfor %}
</ul>
{% endblock %}
{% block footer %}
    {% include "footer.html" %}
{% endblock %}